### ISSUE TITLE
"-header" parameter

### ISSUE THREAD

**Issue by MarcoZufferli** [eslam3kl/SQLiDetector#9]
Hello!

You tool is awesome! Could you try to add a feature where we can insert custom header into all the HTTP Request? for example: sqlidetector -H "hacker1"

**Comment by MindPatch** [comment]
hey @MarcoZufferli , thanks for your suggestion I'll add this feature today

**Comment by jaikishantulswani** [comment]
@eslam3kl Headers are still not implemented as they are not reflecting through proxy.

**Comment by MindPatch** [comment]
@jaikishantulswani could you please provide more information about this ?
I've tested it locally on testphp.vulnweb.com with Zaproxy and it works well
![image](https://user-images.githubusercontent.com/45688522/215263757-6a13298d-10a2-43a5-beda-d9fa675fb2dd.png)

**Comment by jaikishantulswani** [comment]
@knassar702 My bad as I missing adding `value` like  `value: xxyz=x` as I am supplying `xyz=x`
